### ISSUE TITLE
Speed up CI

### ISSUE THREAD

**Issue by oskarth** [oskarth/mopro#9]
# Problem

Right now it takes around 40-50m: https://github.com/oskarth/mopro/actions

Very roughly:
- Install 5m
- Prepare 5m
- Build 25m
- FFI Tests 5m

We want to get this down to <10m before we can use CI to block PRs from merging at this stage.

## Acceptance criteria

CI runs faster, and ideally in <10m

**Comment by oskarth** [comment]
Circom binary cache sketch:

```
jobs:
  # ... other jobs ...

  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Cache circom
        uses: actions/cache@v2
        with:
          path: circom-install  # Directory where we will install circom
          key: circom-binary-${{ hashFiles('**/Cargo.lock') }}  # Assuming Cargo.lock file is in the root of your repository

      - name: Install circom
        if: steps.cache-circom.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/iden3/circom.git
          cd circom
          cargo build --release
          mkdir -p ${{ github.workspace }}/circom-install
          cargo install --path circom --root ${{ github.workspace }}/circom-install

      - name: Prepare CI
        run: ./scripts/prepare_ci.sh

  # ... rest of your jobs ...
```
